### ISSUE TITLE
Miscellaneous Issues with New Views

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#101]
Mike reviewed the state of the views and wrote up the following report.  Migrated from [DDM-1948](https://proj.data.gov.bc.ca/jira/browse/DDM-1948).

**General impressions**

Front page

- "Francais" is a bit gimmicky, imho. It implies that content (dataset descriptions) will be offered in french, or that french search terms can be used. Neither is true
- The three boxes enclosing the words look like buttons, which could be misleading. 
- Hamburger on right - could we use the one used elsewhere on government pages instead?  

**Datasets for an organization** (https://toyger.data.gov.bc.ca/organization/agricultural-land-commission)

- "learn more about this organization" - members list shouldn't be shown if you are not logged in.  
- Organization image is missing
- Facet choices on right should be restricted to the ones that pertain to the datasets in the organization.  And numbers should appear next to the org labels and the facet labels.
- Date formats are messed up and Data Types value is missing  

**Organizations page** (https://toyger.data.gov.bc.ca/organization)

- Clicking on an organization link brings up an empty list of datasets. e.g., https://toyger.data.gov.bc.ca/organization/bc-agency

**Logging in and adding a dataset**

- After logging in I can't see who I am logged in as and I can't get to my profile page (which I need to do in order to get my API Key).  This is what's in the current Catalogue  
- When adding a dataset, State has to be Draft - other choices shouldn't be allowed.
- URL should be populated from the Title
- Organization drop down is empty
- Contacts - organization list is populated, but confusing.  There are parent orgs and sub orgs in the list but that's not obvious.
- There is no save or cancel button at the bottom.  How do I save my new record?

**Miscellaneous**

- Save button is there now, but some mandatory fields are not shown with an *.
- Pressed Save, but got no error or success message
- Can't find the dataset I created
- How do I add a resource?

**Comment by yuisotozaki** [comment]
Assigned to myself so that the issues can be divided and conquered.

**Comment by yuisotozaki** [comment]
**General impressions**

Front page

- "Francais" is a bit gimmicky, imho. It implies that content (dataset descriptions) will be offered in french, or that french search terms can be used. Neither is true (https://github.com/bcgov/ckan-ui/issues/161)
- The three boxes enclosing the words look like buttons, which could be misleading. (https://github.com/bcgov/ckan-ui/issues/120)
- Hamburger on right - could we use the one used elsewhere on government pages instead (https://github.com/bcgov/ckan-ui/issues/167)

**Datasets for an organization** (https://github.com/bcgov/ckan-ui/issues/168)
(E.g. https://toyger.data.gov.bc.ca/organization/agricultural-land-commission)

- "learn more about this organization" - members list shouldn't be shown if you are not logged in.
- Organization image is missing
- Facet choices on right should be restricted to the ones that pertain to the datasets in the organization. And numbers should appear next to the org labels and the facet labels.
- Date formats are messed up and Data Types value is missing

**Organizations page** (Included in https://github.com/bcgov/ckan-ui/issues/168)
- Clicking on an organization link brings up an empty list of datasets. e.g., https://toyger.data.gov.bc.ca/organization/bc-agency

**Logging in and adding a dataset** (https://github.com/bcgov/ckan-ui/issues/169)

- After logging in I can't see who I am logged in as and I can't get to my profile page (which I need to do in order to get my API Key). This is what's in the current Catalogue
- When adding a dataset, State has to be Draft - other choices shouldn't be allowed.
- URL should be populated from the Title
- Organization drop down is empty
- Contacts - organization list is populated, but confusing. There are parent orgs and sub orgs in the list but that's not obvious.
- There is no save or cancel button at the bottom. How do I save my new record? (**Cannot reproduce as of August 25, 2020**)

**Comment by SteveChapmanBCDX** [comment]
This ticket served as a container for several other issues.  All of those issues have been migrated to new tickets.  Closing this ticket.
