### ISSUE TITLE
Visual Refinement

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#197]
Datasets View
- Filter indicator is missing

Dataset View
- Increase padding-top and padding-bottom of button bar to 16px (Adjust the top of Resources box so that it doesn't hide behind the button bar on page load)
- Add 8px padding-top and padding-bottom to Dataset Name
- Display the "Resources" header fully (currently it looks like the cards are pushed up and over the header by 8px)
- Increase the left-hand-side column field separation by adjusting the padding-top and padding-bottom to 8px

Resources View
- "Back to Dataset button" should not remain highlighted on page visit
- Increase padding-top and padding-bottom of button bar to 16px (Adjust the top of Resources box so that it doesn't hide behind the button bar on page load)
- The "Other Resources" header should be the same dimension as the "Resources" header on the Dataset view
- Increase the left-hand-side column field separation by adjusting the padding-top and padding-bottom to 8px
- URL field value should be clickable
- Indent dataset name to align with other fields

Menu
- "Data Catalogue Home" link should link to root

Organization View/GroupView
- Filter set should be higher up on the page
- If you searched in datasets view already, that value shows up again in Organization view. When organization view is loaded, the search field should be empty so that all datasets for that organization are shown by default.

**Comment by yuisotozaki** [comment]
Resource view's field order to be addressed in a different ticket.

**Comment by BrandonSharratt** [comment]
Datasets
- Added this back it was previously removed for the original design merged in PR #79 

Dataset 
- Added py-4 to the button bar (this corresponds to 16px on my screen but not on all screen sizes)
- resources header was made fully visible in other ticket
- Changed pb-0 pt-1 to py-2 on ALL fields, this will fix the name and lefthand side spacing but it will impact ALL forms group/org/resource/dataset

Resources View
- Done not sure why it was showing that here
- Added py-4 px-0 to this instead of pa-0
- Other resources header was made fully visible in other ticket
- the change from dataset to do this affected this screen already
- url field is clickable if it is actually a url and not a file
- done

Menu
- Should there be an item for the datasets list page then?

**Comment by yuisotozaki** [comment]
Menu
As you brought up in the Teams chat, there is a merit for users to being able to go straight to the Datasets view. It is also a standard approach to have a 'home' link in the menu. Let's add "Explore Datasets" and link that to the Datasets view with empty search string and none of the filters applied. This way the user has return path to both the root and the datasets view.

**Comment by BrandonSharratt** [comment]
Menu
- Added second Item and changed old one to home link

Organization View/GroupView
- Removed padding top from the facet filter column(s)
- Currently all of the things tie into one value in the store so if we want the state to be maintained separately it's a bunch more work, alternatively clearing the state on org/group page load would work but would lose any state you had from the datasets page.

**Comment by yuisotozaki** [comment]
All items have been addressed as reported.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
