### ISSUE TITLE
Phase 3 UI Update - Datasets View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#203]
- Display "clear search field" icon when there is a value in the field
- Add a new filter icon when filter is applied
- Rename Published Date to First Published
- Remove Metadata Modified
- Add a label to the filter area 'Filter Search Results'
- Add a filter reset link
- Update filter terminology:
  - Licenses -> Licence
  - Data Types -> Resource Data Types
  - State -> Record Status
  - Organization -> Source Organization
- Search field should be reset to blank when returning to 'Home' or 'Explore Datasets' or 'Explore by Organization' or 'Explore by Groups'
- Add 'Tracking' option to the footer just like in catalogue.data.gov.bc.ca (see second picture attached)

![Datasets View - Desktop.png](https://images.zenhubusercontent.com/5e3c6715d85e5dced833aef6/70210e67-5e18-4da1-9925-fc178413f488)

![Group 573](https://user-images.githubusercontent.com/56084999/94750334-a966b880-033a-11eb-8ebd-626bb9325fa3.png)

**Comment by BrandonSharratt** [comment]
_Display "clear search field" icon when there is a value in the field_
Done, note that clicking the search icon before would search so that functionality has been removed

_Add a new filter icon when filter is applied_
Done

_Rename Published Date to First Published_
Done

_Remove Metadata Modified_
Done

_Add a label to the filter area 'Filter Search Results'_
Done, note that on my 15" monitor it has to be split onto two lines, so we have removed most of the gutter between the results and the filters have been removed, this has been applied to all "search" pages (group view, org view, datasets page)

_Add a filter reset link_
_Update filter terminology:
Licenses -> Licence
Data Types -> Resource Data Types
State -> Record Status
Organization -> Source Organization_
Done, note that you might need to delete your cache for this to show up

_Search field should be reset to blank when returning to 'Home' or 'Explore Datasets' or 'Explore by Organization' or 'Explore by Groups'_
Currently these are stored in the cache and would require separating them out and more work these should be there own ticket if we still want this

_Add 'Tracking' option to the footer just like in catalogue.data.gov.bc.ca (see second picture attached)_
Done but note that I made it more closely match the dialogs we already have e.g. About. Basically the title bar is blue.

**Comment by yuisotozaki** [comment]
I'll create a separate ticket for clearing the search field - it was confusing the user switching between views (datasets to organizations to groups).

**Comment by SteveChapmanBCDX** [comment]
Outstanding issues:
* Update filter terminology => "Organization" to "Source Organization"
* Filter Search Results and related buttons in line

@yuisotozaki - Can you review the outstanding issues?  Probably best create a new ticket for those items and close this one.

**Comment by yuisotozaki** [comment]
Reviewed outstanding issues:
* I will raise a new ticket for renaming 'Organization' filter header
* There's not enough space to put 'Filter Search Results' and buttons in-line - so we're good to move on from this one.

Ready to close this ticket. @SteveChapmanBCDX

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
