### ISSUE TITLE
Dataset View: Design

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#36]
Design the dataset view.

**Comment by yuisotozaki** [comment]
Dataset View design notes and screenshots.
https://documize.pathfinder.gov.bc.ca/s/bkph5eb5fb79okvk8ffg/data-discovery-and-management/d/bp261mnf7ss5649lh7h0/bcdc-uiux-design-notes?currentPageId=bp67etvf7ss5649lh8cg

**Comment by jachurchill** [comment]
Concerns mentioned during this morning's UI/UX meeting:
- Dataset fields cannot be sorted to a custom layout as the front end does not know what they are
- The categories cannot be added to group fields as again the front end does not know what the fields are
- For the resource list I think the assertion that the title is unnecessary because it's obvious is not necessarily true for public users and it would be helpful for overall clarity
- Again in the resource list the main function that most users do is download/access the data, I would suggest that maybe that button should be outside the ellipsis menu
- Not sure about the delete confirmation being in primary blue, it's fairly significant to delete a resource and it struck me that red might confirm the severity more effectively
- For the help dialogue since we can't do sub categories there can't be help on those, they can only be attached to individual fields (top level is possible on composite fields like contact) since most will be smaller might be better to use a popover instead of a modal

@BrandonSharratt  do you have any further feedback?
cc @nanyangpro @yuisotozaki @SteveChapmanBCDX

**Comment by SteveChapmanBCDX** [comment]
My responses to John's comments above:

1. No comment.
2. No comment.
3.  **Agree** - Recommend we keep header that reads "Data and Resources" or simply "Resources".
4.  **Disagree** - I think we can keep the download action inside the three-dot menu.
5.  **Unsure** - I think blue is OK - I would defer to UI/UX design team on this one.
6.  I don't think it makes sense to add help dialogue controls anywhere other than where they were located in the designs.  If current code does not support this location, we may have to consider changes to code.

**Comment by yuisotozaki** [comment]
Design Update Summary
1. Dataset View's field order updated according to sample JSON file
2. Dataset View's field groupings updated according to sample JSON file
3. Sub-header renamed to "Resources" and also added Sub-header for "Dataset Details" to visually balance the two sides of the page
4. Download action will remain in the three-dot-menu
5. Delete confirmation button colour updated to red
6. Help dialog access icons added to individual fields that are not part of composites and also on the composite field itself.

*Changes applied to both desktop and mobile versions.
