### ISSUE TITLE
Long Values being Trunctated with ...

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#372]
Long values are now being truncated with a ...
1.9.0-c386025Api Version: 2.7.5

**Issues:**
* Consumer cannot see or copy the full value entered by the client.
* Items like More Info URL should allow for the full value to be visible to assist with distinguishing what the URLs are without clicking on each.
![image](https://user-images.githubusercontent.com/32690119/109863756-dfc0a080-7c16-11eb-8585-f58b8828fb1c.png)

* Contact Name now makes the users name unreadable.
![image](https://user-images.githubusercontent.com/32690119/109863661-c15aa500-7c16-11eb-9291-ceca8c7967be.png)

**Suggestion:**
* Allow different sections have different indents as the white space between label and value is huge.
* Wrapping can occur but should just alight with or in front of the Label.

**Comment by annikaLiving** [comment]
@yuisotozaki  for comment. :)

**Comment by yuisotozaki** [comment]
For Contact fields, we should show the values so that it's human legible.
For More Info, the current behaviour came from the design when we wanted to display all of Description field value plus a truncated URL value. Since Description field is new and so none of the More Info values in current cat has a Description, we should show the whole URL value.

If Description is provided for new metadata in the future, we want to only show the Description text hyperlinked with the URL provided. When we do this, the entire Description field value should be visible.

**Comment by BrandonSharratt** [comment]
As I mentioned when I added the ... truncation to more info that it would affect all composite repeating fields. Contact is also a composite repeating field. 

Yes I can add hover text to truncated urls

**Comment by sheilamv** [comment]
It appears that Contact has hover text (/)
It appears that URLs with ... has hover text to show full ULR (/)
