### ISSUE TITLE
Tool Tips

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#428]
Creation of Tool Tips on fields.

**Comment by yuisotozaki** [comment]
Observations on version: 1.9.0-86d3144
1. Tooltips activate when hovered over. This can become too much past the initial onboarding for users. Recommend making tooltips click-activated.
2. Tooltip container grows horizontally to the edge of the screen. E.g. Some of the longer definitions can span the screen horizontally, making it difficult to read the content. Recommend containing the tooltip container to about 500px.
3. Tooltip text containing HTML tags are not rendering the HTML tags properly. E.g. Security Classification. Recommend enabling HTML rendering.
4. Tooltip icons currently follow the end of the field label text. This can be perceived as visually distracting. Recommend right justifying the icons to the edge of the field label container so that they show up in a straight vertical line.
5. Tooltip icon colour may have too much contrast, distracting the user from content. Recommend experimenting with  hex:38598A.

**Comment by annikaLiving** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/33

**Comment by sheilamv** [comment]
Passed.
