### ISSUE TITLE
View JSON button is displayed in the top button bar regardless

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#455]
There's a View JSON button in the button bar that doesn't belong there.
Version: 1.9.0-e825c50Api Version: 2.7.5
![image.png](https://images.zenhubusercontent.com/5e3c6715d85e5dced833aef6/6ebbdb5a-474e-4d87-a926-5d525810c015)

**Comment by TerryLanktree** [comment]
@BrandonSharratt  Is this functionality ready to Production? We need to hide it or make the button better.  There are other tickets on this issue, need to understand the user story.

**Comment by sheilamv** [comment]
@TerryLanktree , I am not sure why there is the button or how it got implemented.  It should be removed, but the whole JSON implementation needs attention.

**Comment by BrandonSharratt** [comment]
It was implemented as part of my work on DIP they asked for it to be added and it was approved a long time ago. There were a few bugs that have since been resolved around it. It should only show if there is json table schema provided or it was able to infer the information from a csv, the latter implies the csv is previewable as well.
