### ISSUE TITLE
413 - Request Entity Too Large (includes BETA feedback)

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#457]
A 413 Request Entity Too Large happens for some medium size requests, large enough that they aren't small but small enough that they shouldn't be a problem investigate.

**Comment by BrandonSharratt** [comment]
This was happening on the node server side as the default limit is 100kb, Caddy bypasses the express server for file upload so it wasn't noticed except on very filled in dataset/resource combos. 

I have increased the size to 10Gb which should be large enough to not give us any problems, if we start uploading files on the ui side we can revisit.

**Comment by sheilamv** [comment]
@BrandonSharratt , can this be tested in Beta, or just Toyger?

**Comment by sheilamv** [comment]
Can this only be tested using the API?  It appears from a comment above from @BrandonSharratt, that leads me to believe the fix was not intended for the uploading of files using the UI.  

cc @TerryLanktree

**Comment by TerryLanktree** [comment]
@sheilamv please test the UI with a file > 100kb, that will tell us if there is still an issue.

**Comment by sheilamv** [comment]
We encountered an issue from an Editor doing beta testing.  I followed the steps to reproduce and was able to reproduce the issue.  

Email from Editor and my Reply:

Good Morning Terrence,

Thanks so much for providing this feedback.  It is great to see the steps you took so we could reproduce the issue.  

1.	I will enter your enhancement request regarding the Editor Dashboard
2.	You have found a defect which has been reported.
a.	I downloaded the existing file from the URL in the resource record (33 MB)
b.	I tried to upload it as a ‘file’ and encountered the same result as you (spinning circle and noting has been saved)

I believe the issue is the size of the file you are trying to upload.  If you can let me know the size of the file you were trying to upload, that would be most helpful.  As you can see I tried to upload the existing file attached to the resource record to preserve the resource.  

Thanks again for these items.  Feel free to continue to poke around the application and provide feedback.  Have a wonderful day!

Regards,

Sheila Vander-Hoek (CITZ)

From: Branscombe, Terrence EMLI:EX <Terrence.Branscombe@gov.bc.ca> 
Sent: Monday, July 19, 2021 4:30 PM
To: DataBC CITZ:EX <Data@gov.bc.ca>
Subject: BETA: data catalogue testing - uploads working?

HI,

Good to see a new beta and hammer away on it.  I have one suggested 'feature' and a bit of a bug report on the beta.

The 'feature' I'd like to see, as an Editor of one or more datasets, is to see a dashboard of my datasets when i first login with IDIR.  Right now, I have to search for them each time.

The 'bug' may not be a bug, but I tried uploading a new version of one dataset using these steps:

1.            Login with IDIR
2.            Search for dataset "Provincial Oil and Gas Tenure Registry Extract (non-confidential records)"
3.            Click the pencil icon on top to "Edit  Resource"
4.            Select the 'File' radio button in the Resource section
5.            Click inside the Name* field and select the file to upload to the Catalogue
6.            Click 'Save' at top left
7.            Result: the rotating circle segment appears, but the upload never completes and the progress bar continues turning.

Thanks,

--
Terrence Branscombe
Senior Tenure Management Advisor
Tel  (778) 698-3683 

WWW: Tenure and Geoscience Branch

**Comment by sheilamv** [comment]
@TerryLanktree , what size should be the maximum that can be uploaded through the UI?

**Comment by sheilamv** [comment]
Additional comments from Terrence:
I was trying to upload a file of almost the same size as the original, about 33 MB.  This is very typical for this particular data resource upload; the month-to-month variations are very small.  Hope this helps.

Thanks agains,
--
Terrence Branscombe

**Comment by joe-taylor** [comment]
Besides the Caddy limit Brandon described above, there is a configurable max upload size in CKAN itself. This can be modified with `ckan.max_resource_size` which defaults to 10MB. I believe the issue is that we are running into that upload limit, although there may also be a bug in some validation code which is confounding this further.

At any rate, I recommend increasing the upload limit to 300MB.

**Comment by TerryLanktree** [comment]
Please increase and we can test if this is the last pinch-point.

**Comment by joe-taylor** [comment]
Although increasing the size alone appeared to be sufficient in dev, where the upload limit was 10MB and is now 100MB, I've now discovered that in beta the current upload limit is 50MB. This should cover the 33MB upload in question, so it appears this is not root cause for the failures in beta.

I can see from the error console however that there is a mistake in the validation code. File  objects are being validated as URLs and this is triggering errors when it occurs. I'll make a few code changes to rectify this.

**Comment by sheilamv** [comment]
@joe-taylor , @annikaLiving  - has the file been moved from cati for this resource?

https://toyger.data.gov.bc.ca/dataset/provincial-oil-and-gas-tenure-registry-extract-non-confidential-records-/resource/4bc42b04-f126-4f91-90de-804b27cd51f2

It is a **URL**, and I am trying to change to **file** and upload what I downloaded to reproduce the issue. 

I now get an 'unknown error' when attempting to upload and save a file (ips_extract.zip) which is 33,762kb.

**Comment by sheilamv** [comment]
I tried to create a new resource on the dataset and got the same error.

**Comment by joe-taylor** [comment]
This is a new one for me, but I can confirm that I'm seeing that same error although it was working for me previously. From the JavaScript console, it appears to be a 409 conflict error, but I'll have to do some more digging to find out why that's happening now.

**Comment by joe-taylor** [comment]
I'm thinking `ckan.max_resource_size` didn't carry over to cati.

**Comment by joe-taylor** [comment]
I just confirmed that the problem was a config change that needed to be made in toyger. In that environment, the max_resource_size was 10MB. I've updated it to 300MB as per above, and personally confirmed that a 33MB uploads works with that config.

**Comment by sheilamv** [comment]
**Passed**.  Able to upload the file directly to the resource.

**Comment by sheilamv** [comment]
FYI - as per @annikaLiving , Production upload limit is 150MB.  Can anyone confirm that?

**Comment by joe-taylor** [comment]
@sheilamv Yes, that is correct, and beta's limit should have been updated, either today or last night, to 300MB from 50MB.

**Comment by sheilamv** [comment]
Tested as sysadmin, admin and editor and PASSED
