### ISSUE TITLE
Learn more about this group link is not displaying newly created group's description text

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#495]
Migrated group data is displaying the description text when viewing from Learn more about this group.  However, when you create a new group directly in Beta, add optional description text, the system is not displaying it when viewing under Learn more about his group menu option.  

![image.png](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/52ad4985-4d97-436b-a10d-3186d74fc673)

![image.png](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/fe6dd094-6dfa-4b40-83a0-cbf4d79424da)

**Comment by joe-taylor** [comment]
This appears to be another schema issue; instead of using the existing `description` field for groups, a new field was created called `notes`. By all appearances, both are intended for the same purpose. The only difference is in where they are used. The `notes` field is what ckan-ui saves to from the edit screen, and the `description` field is what it consults for the info modal.

A fix could conceivably be applied to either ckanext-bcgov-schema or this repository. My preference is to apply the fix in the schema repo if it's possible to do there.

**Comment by joe-taylor** [comment]
This issue was resolved by the schema patch, but to keep a clean house I'm sending through one final PR to remove some UI code referencing the `notes` field. It's a branching path reachable only if `description` doesn't exist. There's no need to complicate things with fallback fields. The `notes` field shouldn't be used.

**Comment by sheilamv** [comment]
_Testing STR:_

1. Logged in as SysAdmin (shevande)
2. Hamburger > Explore Dataset Groups
3. Select [Add Group] button
4. Create a new group, filling in all details (NOTE:  when I started to created the Name, the URL was not created like it does when creating a dataset)
5. Refresh Group list page
6. Select the newly created group
7. Select Learn more about this group

**Expected**:  I would be able to see the optional description I added on creation
**Actual**:  As expected

**PASS**

**Comment by sheilamv** [comment]
Testing STR in Beta:

1. Logged in as SysAdmin (shevande)
2. Hamburger > Explore Dataset Groups
3. Select [Add Group] button
4. Create a new group, filling in all details (NOTE: when I started to created the Name, the URL was not created like it does when creating a dataset)
5. Refresh Group list page
6. Select the newly created group
7. Select Learn more about this group

**Expected**: I would be able to see the optional description I added on creation
**Actual**: As expected

**PASS**
