### ISSUE TITLE
Slide Deck - UI/UX Improvements Plan

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#50]

**Comment by yuisotozaki** [comment]
# Meeting Minutes from Meeting with Brittany re: Improvement Plan Slide Deck
What does 'modernize' mean?
Will each point be supported in Documize so that all Q&A can be redirected?
Recommend what activities we can do for phase 2 and phase 3.
BCDC is not quite sure if there is enough data to direct efforts to high value items.
- Recommend how to approach feedback collection
- Many 'pain points' are anecdotal at best
- Previous UX research didn't dive into the reasons behind the pain points
- False negatives (non-existence of data) were confusing - users could not figure out if that data didn't exist or the search terms were not good enough
- Rebekkah has tickets where data requests from users where the data did exist but the search didn't surface the data - BCDC is not sure exactly what the root cause of this symptoms are
'Editor' vs 'Data Provider' (See notes below 'Types of clients')
Gen (ED) is very keen on making sure that the intermediary documentation is available in Documize.
- Artifacts such as observation notes rather than just the final summary
How does the timing look like?
- Mention timeline for user testing schedule in the slides
- Dependent on implementation timeline (need input from dev)
Geospatial clients are the biggest clients but don't want to skew priority going forward
- Not just open data or spatial data
Rebekkah can help us with coordination and communication

Types of clients
- Consumers
- Suppliers (provides data)
- Partners (strategic clients) IIT (natural resources) and GeoBC
- Hybrid (provider as well as consumers)
This means given a specific individual, they can switch roles between these types
Depending on the product/service, the actual label for them will change
BCDC aims to understand their client business needs to figure out what type of users the client organization has - e.g. if the client is mandated to provide data, the end-user may be a reluctant user.

We need to make sure that we manage user expectation during testing that they are 'consumers'.

For the user testing outreach, CE will need a short description of what, when, where so that the clients can figure out if they are interested -> Invitation email draft.

# Actions
- Revise slide deck (timeline slide, reference to documize)
- Recommend how to collect external non-gov user feedback for phase 2 work
- Draft email invitation describing the nature of the user testing

**Comment by yuisotozaki** [comment]
# Outstanding Discussion
* Can we continue to run Google Analytics to find intersection of drop-offs and user feedbacks?

**Comment by nanyangpro** [comment]
[BCDC UX Improvement Plan.pptx](https://github.com/bcgov/ckan-ui/files/4327036/BCDC.UX.Improvement.Plan.pptx)

**Comment by SteveChapmanBCDX** [comment]
Nan moved the slide deck above to `DDM_BCDC > Design Notes` directory in Teams.  Closing ticket.
