### ISSUE TITLE
Update About menu to remove the 'For Technical Support' section for Beta

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#506]
For Beta only, please comment out the _DataBC Service Desk_ link under the **For Technical Support** section to not confuse the testers.  

Add temporary text for Beta:

•	Send to [data@gov.bc.ca](data@gov.bc.ca) with Subject Line starting with “BETA:”.

**Comment by cpspicer** [comment]
For beta 'stage 3' - public

**Comment by joe-taylor** [comment]
I've updated the about modal in beta to include the temporary text referenced above, and commented out the previous message. There is no pull request associated with this because the content is stored in the database rather than in code.

![image](https://user-images.githubusercontent.com/5297264/126749147-24446009-868d-4581-9f50-af664bd9ee14.png)
