### ISSUE TITLE
Datasets View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#55]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- The left and right edges of the content flow should align with what’s in Header and Footer.
- Should increase the distance between the left section and the right section so that they are visually more separated from each other.
- The distance between Header and the content flow should be 50 pixels.
- The distance between the content flow and Footer should be 50 pixels.
- The position of the right section should be fixed instead of static.

### Search Bar
- Background color should be #FFFFFF.
- Border should be 2px solid #003366.
- Border-radius should be 3px.
- The Search icon should be #CCCCCC.

### Dataset Count
- Text should be on one line.
- “18 datasets found matching "Bear" and with 1 filter applied” should be “18 datasets found” with the search term left in the search box.

### “Order by”
- Text should be #494949.
- Remove the extra space between the text and the dropdown indicator.

### Dataset List
- Reduce the distance between rows within each dataset, and increase the distance between datasets so that the datasets are visually more separated from each other.
- Text should be BC Sans - Regular - 14px - #494949.
- Add space after “Data Types:” and each comma.

### Pagination Control
- Since Vuetify's pagination control separates each page number in a button-like construct, leave default amount of space in between as seen in their example. https://vuetifyjs.com/en/components/paginations/
- Should be aligned to the left.
- Should use the default chevron-left and chevron-right icons.

### Expand All | Collapse All
- Should have the same functionalities as indicated by the text.
- Should be top-aligned with the search results for visual balance, understanding that it does introduce perceived wasted space.
- Should have the same paddings as the filter header (e.g.Licenses, Data Types)
- The height should be 40 pixels.
- Background colour should be #38598A.
- Border-radius should be 0.

### Filters
- When expanded beyond original browser viewport height, the filter container should not overlap the footer (E.g. Expand organization and scroll all the way to the bottom to see the effect).
- Since we're using Vuetify expansion panels, we could try keeping the unfocused headers together.

### Filter Criteria Titles
- The height should be 50 pixels and not change between collapsed and expanded state.
- Font should be bold.
- Increase the distance between bottom and the first row of the labels.
- Show text “Login with your IDIR to use this filter.” if a logged in-only filter label exists (E.g. State).

### Filter Criteria Labels
- The height should be 42 pixels.
- Should have #1A5A96 16px regular text, #FFFFFF background with 1px border #DDDDDD, and #1A5A96 16x16 icon if not applied.
- Should have #FFFFFF 16px bold text, #1A5A96 background with no border, and #FFFFFF 16x16 icon if applied.
- Nice-to-have if the applied filter labels are listed first before the options that are not applied (E.g. if "pdf" is applied in Data Types, it should be the first filter option in the list).

**Comment by BrandonSharratt** [comment]
Overall
_Font should be BC Sans._
Done

_Background color should be #F2F2F2._
Done

_The left and right edges of the content flow should align with what’s in Header and Footer._
Done

_Should increase the distance between the left section and the right section so that they are visually more separated from each other._
Done however note the only way to do this was to decrease the size of the results

_The distance between Header and the content flow should be 50 pixels.
The distance between the content flow and Footer should be 50 pixels._
Hard pixel amounts don't scale well with window size/mobile I've instead added my-4

_The position of the right section should be fixed instead of static._
If It's fixed you can't scroll beyond the bottom of the screen and the filters expand below the bottom of the screen often.

**Comment by BrandonSharratt** [comment]
Search Bar
_Background color should be #FFFFFF._
Done
_Border should be 2px solid #003366._
Done
_Border-radius should be 3px._
Done
_The Search icon should be #CCCCCC._
Done

**Comment by BrandonSharratt** [comment]
Dataset Count
_Text should be on one line._
What does this mean? Assuming it ties into the below we can't guarantee it will be on one line across all screen sizes
_“18 datasets found matching "Bear" and with 1 filter applied” should be “18 datasets found” with the search term left in the search box._
Done removed filter notification and search term notification

**Comment by BrandonSharratt** [comment]
“Order by”
_Text should be #494949._
Done
_Remove the extra space between the text and the dropdown indicator._
If I make it any smaller it splits to two lines. It already splits to two lines on smaller screens

**Comment by BrandonSharratt** [comment]
Dataset List
_Reduce the distance between rows within each dataset, and increase the distance between datasets so that the datasets are visually more separated from each other._
Added py-0 my-0 to all rows in dataset and mb-4 to the container

_Text should be BC Sans - Regular - 14px - #494949._
Text change happened as part of overall change. Colour changed

_Add space after “Data Types:” and each comma._
Done

**Comment by BrandonSharratt** [comment]
Pagination Control
_Since Vuetify's pagination control separates each page number in a button-like construct, leave default amount of space in between as seen in their example. https://vuetifyjs.com/en/components/paginations/_
Done

_Should be aligned to the left._
Done

_Should use the default chevron-left and chevron-right icons._
Done

**Comment by yuisotozaki** [comment]
> Dataset Count
> _Text should be on one line._
> What does this mean? Assuming it ties into the below we can't guarantee it will be on one line across all screen sizes
Yep, that's fine - we saw that the text was still on 2 lines on a full desktop resolution. As long as it starts that way and wraps only when necessary, we're good with that.

**Comment by yuisotozaki** [comment]
> “Order by”
> _Text should be #494949._
> Done
> _Remove the extra space between the text and the dropdown indicator._
> If I make it any smaller it splits to two lines. It already splits to two lines on smaller screens

Understood!

**Comment by BrandonSharratt** [comment]
Expand All | Collapse All
_Should have the same functionalities as indicated by the text._
They do?

_Should be top-aligned with the search results for visual balance, understanding that it does introduce perceived wasted space._
Done

_Should have the same paddings as the filter header (e.g.Licenses, Data Types)_
Done

_The height should be 40 pixels._
Done

_Background colour should be #38598A._
Done

Border-radius should be 0.
Done

**Comment by BrandonSharratt** [comment]
Filters
_When expanded beyond original browser viewport height, the filter container should not overlap the footer (E.g. Expand organization and scroll all the way to the bottom to see the effect)._
Not happening for me, could be because of previous changes in this ticket

_Since we're using Vuetify expansion panels, we could try keeping the unfocused headers together._
They are not grouped together they are individual due to implementation constraints

**Comment by BrandonSharratt** [comment]
Filter Criteria Titles
_The height should be 50 pixels and not change between collapsed and expanded state._
Done

_Font should be bold._
Done

_Increase the distance between bottom and the first row of the labels._
Done

_Show text “Login with your IDIR to use this filter.” if a logged in-only filter label exists (E.g. State)._
Not sure what you mean here, all of the headers show up whether you are logged in or not. Do you want to show that text when they get more options if they are logged in because we have no way of knowing if thats the case it's also confusing because the filter does work if they aren't logged in

**Comment by BrandonSharratt** [comment]
Filter Criteria Labels
_The height should be 42 pixels._

_Should have #1A5A96 16px regular text, #FFFFFF background with 1px border #DDDDDD, and #1A5A96 16x16 icon if not applied._
Done

_Should have #FFFFFF 16px bold text, #1A5A96 background with no border, and #FFFFFF 16x16 icon if applied._
Done

_Nice-to-have if the applied filter labels are listed first before the options that are not applied (E.g. if "pdf" is applied in Data Types, it should be the first filter option in the list)._
Done

**Comment by yuisotozaki** [comment]
![image](https://user-images.githubusercontent.com/56084999/78831645-d5623c00-799e-11ea-83f6-cf533c43d915.png)
Alignment, visualized.

**Comment by yuisotozaki** [comment]
More alignment visualized.
![image](https://user-images.githubusercontent.com/56084999/78832059-8072f580-799f-11ea-81db-457ee5fb500d.png)

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Overall

- Background color should be #F2F2F2.
- The left and right edges of the content flow should VISUALLY (remove extra padding or margin?) align with what’s in Header and Footer.
- The position of the right section should be fixed instead of static (scrollable separately from the left section when expanded). We want the user to have access to the filter wherever the user is vertically on the datasets list.

### Search Bar
- The Search icon should be #CCCCCC.

### Dataset Count
- Text should be on one line (redefine columns for the Dataset Count and “Order by”? The extra col-3 in between eats up horizontal space and forces those 2 components to be on multiple lines when there’s still space in between visually).

### “Order by”
- Text should be #494949 (options and the dropdown indicator should be the same color as well).
- Remove the underline when clicked on.

### Dataset List
- Increase the distance between datasets a bit more so that the datasets are visually more separated from each other. (Or instead, set description line-height to 1.3)
- Text should be BC Sans - Regular - 14px - #494949 (please make the font-size smaller here as they are visually too strong now).

### Pagination Control

### Expand All | Collapse All
- Should have the same functionalities as indicated by the text (currently not working for us).
- Should be top-aligned with the search results (VISUALLY, it’s now aligned with the description of the first dataset, please see the mockup for reference), understanding that it does introduce perceived wasted space.
- The height of the bar should be 40 pixels only.
- Border-radius should be 0.
- Please see the mockup for reference regarding the visual look and feel, and remove the button-like shadows and interactions.

### Filters
- The height of the bar should be 40 pixels only.
- Border-radius should be 0.

### Filter Criteria Titles
- The height of the bar should be 40 pixels only.
- Border-radius should be 0.

### Filter Criteria Labels
- Should have #1A5A96 16px regular text, #FFFFFF background with 1px border #DDDDDD, and #1A5A96 16x16 icon if not applied.
- Should have #FFFFFF 16px bold text, #1A5A96 background with no border, and #FFFFFF 16x16 icon if applied.
- Please use the same color scheme as indicated in the mockup. Blue #1A5A96. White #FFFFFF (details above).
- Remove the applied filter label count indicator in the titles.

**Comment by jachurchill** [comment]
Overall
* Background color should be #F2F2F2.
    * Done
* The left and right edges of the content flow should VISUALLY (remove extra padding or margin?) align with what’s in Header and Footer.
    * Done
* The position of the right section should be fixed instead of static (scrollable separately from the left section when expanded). We want the user to have access to the filter wherever the user is vertically on the datasets list.
    * Not Done, expands too much to see
Search Bar
* The Search icon should be #CCCCCC.
    * Done
Dataset Count
* Text should be on one line (redefine columns for the Dataset Count and “Order by”? The extra col-3 in between eats up horizontal space and forces those 2 components to be on multiple lines when there’s still space in between visually).
    * Done
“Order by”
* Text should be #494949 (options and the dropdown indicator should be the same color as well).
    * Done
* Remove the underline when clicked on.
    * Done
Dataset List
* Increase the distance between datasets a bit more so that the datasets are visually more separated from each other. (Or instead, set description line-height to 1.3)
    * Done
* Text should be BC Sans - Regular - 14px - #494949 (please make the font-size smaller here as they are visually too strong now).
    * Done
Pagination Control
Expand All | Collapse All
* Should have the same functionalities as indicated by the text (currently not working for us).
    * Looking into
* Should be top-aligned with the search results (VISUALLY, it’s now aligned with the description of the first dataset, please see the mockup for reference), understanding that it does introduce perceived wasted space.
    * Done
* The height of the bar should be 40 pixels only.
    * Done
* Border-radius should be 0.
    * Done
* Please see the mockup for reference regarding the visual look and feel, and remove the button-like shadows and interactions.
    * Done
Filters
* The height of the bar should be 40 pixels only.
    * Done
* Border-radius should be 0.
    * Done
Filter Criteria Titles
* The height of the bar should be 40 pixels only.
    * Done
* Border-radius should be 0.
    * Done
Filter Criteria Labels
* Should have #1A5A96 16px regular text, #FFFFFF background with 1px border #DDDDDD, and #1A5A96 16x16 icon if not applied.
    * Done
* Should have #FFFFFF 16px bold text, #1A5A96 background with no border, and #FFFFFF 16x16 icon if applied.
    * Done
* Please use the same color scheme as indicated in the mockup. Blue #1A5A96. White #FFFFFF (details above).
    * Done
* Remove the applied filter label count indicator in the titles.
    * Done

**Comment by SteveChapmanBCDX** [comment]
Ticket completed - closing.
