### ISSUE TITLE
Beta SOLR - Ensure critical fields are searchable 

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#550]
Now that some fields have moved from the package to the resource level, some of these may need to be configured in SOLR to be searchable.

For example object_name, which is a highly searched item from the API.

This in prod works
https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=object_name:WHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP

But this does not but should
https://cat.data.gov.bc.ca/api/3/action/resource_search?query=object_name:WHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP

**Comment by annikaLiving** [comment]
@TerryLanktree  i think this is something that you need to review ASAP for when we send this out to API users to review.

**Comment by joe-taylor** [comment]
Resource level fields can be made searchable using ckan.ini config changes such as the following:

```ini
## Make more resource fields searchable
ckan.extra_resource_fields =
    bcdc_type object_name
```

This exposes fields like object_name for search using API calls like the following:

`/api/3/action/package_search?q=res_extras_object_name:*`

I've moved this config change through to dev for testing.

**Comment by joe-taylor** [comment]
Based on a naive comparison of fields in production and dev (naive because fields may be present in both environments but distributed or represented completely differently), and ignoring fields with numbers in them like `extras_details111data_precision`, the following differences were flagged for review. @annikaLiving

**Fields in production but not in dev**

extras_east_bound_longitude  
extras_image_url  
extras_layer_name  
extras_link_to_imap  
extras_north_bound_latitude  
extras_preview_image_url  
extras_preview_latitude  
extras_preview_longitude  
extras_preview_map_service_url  
extras_preview_zoom_level  
extras_south_bound_latitude  
extras_west_bound_longitude

**Fields in dev but not in production**

extras_contacts  
extras_dates  
extras_more_info  
extras_publish_state  
res_extras_bcdc_type *- added by config change referenced above*   
res_extras_object_name *- added by config change referenced above*   
res_type

**Comment by joe-taylor** [comment]
If we'd like to customize any of the above, we have the option to make config changes, as mentioned, or we can [hook into the solr update using our plugin](https://github.com/bcgov/ckanext-bcgov/blob/e6aad2bb6dc23607b5febd4a3f0b15c48814db13/ckanext/bcgov/plugin.py#L248).

**Comment by joe-taylor** [comment]
I have ported config changes to beta to support `object_name` field queries. Here is a working query which returns all the datasets that have resources with an `object_name`. Note the difference in the beta and prod urls, which is the inclusion of **res_extras_** in the former.

**Beta:** [https://beta-catalogue.data.gov.bc.ca/api/3/action/package_search?q=<b><i>res_extras</i></b>_object_name:*](https://beta-catalogue.data.gov.bc.ca/api/3/action/package_search?q=res_extras_object_name:*)  
**Prod:** [https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=object_name:*](https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=object_name:*)

Returning records with a specific `object_name` is also possible:

**Beta:** [https://beta-catalogue.data.gov.bc.ca/api/3/action/package_search?q=<b><i>res_extras</i></b>_object_name:%22WHSE_ARCHAEOLOGY.RAAD_SUBSURFACE_TEST_AREAS_SP%22](https://beta-catalogue.data.gov.bc.ca/api/3/action/package_search?q=res_extras_object_name:%22WHSE_ARCHAEOLOGY.RAAD_SUBSURFACE_TEST_AREAS_SP%22)  
**Prod:** [https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=object_name:%22WHSE_ARCHAEOLOGY.RAAD_SUBSURFACE_TEST_AREAS_SP%22](https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=object_name:%22WHSE_ARCHAEOLOGY.RAAD_SUBSURFACE_TEST_AREAS_SP%22
)

It is now a matter of deciding if any of other extras fields are needed for MVP, bearing in mind that query functionality that was available before (especially for numeric values) may not be readily duplicated for some of the fields now that they're associated to dataset resources instead of the datasets themselves. 

My assessment so far is `link_to_imap` may be useful but general preview bounds information is likely not. That is because Solr sees latitude for example as an array of values rather than a single number, so combining it with a query on longitude for example is unlikely to work the same as before.

**Comment by alixcote** [comment]
@annikaLiving to review Joe's latest comments.

**Comment by annikaLiving** [comment]
@joe-taylor your change seems to have also made this work, which is very positive! :)

https://beta-catalogue.data.gov.bc.ca/api/3/action/resource_search?query=object_name:WHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP

**Comment by annikaLiving** [comment]
Reviewing this following documentation to see what info they obtain via the api. ALso confirming with others internally if we need to add other items.

https://github.com/bcgov/bcdata/blob/catalogue-api-changes/inst/service_documentation.md

**Comment by joe-taylor** [comment]
> @joe-taylor your change seems to have also made this work, which is very positive! however this only returns the resources with this object name, however still returns the package ID will is needed either way.
> 
> https://beta-catalogue.data.gov.bc.ca/api/3/action/resource_search?query=object_name:WHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP

Although the config changes I made will also allow you to perform queries on those fields using `resource_search`, note that this behaves very differently from `package_show`. That's because the former [uses database queries](https://github.com/ckan/ckan/blob/ckan-2.7.5/ckan/logic/action/get.py#L2115-L2119) and the latter uses Solr.

Because of this fundamental and significant difference, `resource_search` can lead to some surprising results. For example, `resource_search` performs a *substring* query rather than searching for exact matches, so you may end up getting more results than you expect.

 - [https://beta-catalogue.data.gov.bc.ca/api/3/action/resource_search?query=object_name:WHSE_WILDLIFE_MANAGEMENT.WAA_](https://beta-catalogue.data.gov.bc.ca/api/3/action/resource_search?query=object_name:WHSE_WILDLIFE_MANAGEMENT.WAA_)
