### ISSUE TITLE
Page Titles for SEO

### ISSUE THREAD

**Issue by alixcote** [bcgov/ckan-ui#551]
HTML Header fields for each record they should reflect the title of the dataset to help search engines like google index and rank the page and make it easier for users to find. It will use what is in this header and the description to display its results also.

Old catalogue HTML Head section

Forest Road Segment Tenure - Data Catalogue 
<title>Forest Road Segment Tenure - Datasets - Data Catalogue</title>

 

BCDC Data Catalogue 
<title>BCDC Data Catalogue</title>

**Comment by joe-taylor** [comment]
I used what we have in the current production catalogue as my guide. I've updated the titles to be set dynamically, according to a routes' loaded content, as follows. I *believe* that Google will pick up on these titles changes. If it doesn't, we may have to go back to the drawing board and rearchitect things. I resorted to a hacky approach, setting the title via computed state, since doing it at the router level would require a significant refactoring. While Google may pick up these changes it is probable that some search engines will not; in fact, some search engines likely won't crawl our website once it's structured as a client side Vue app.

**Datasets (view)**
<del>Viewing Dataset</del>
`dataset name` - Datasets - Data Catalogue

**Resources (view)**
<del>Viewing Resource</del>
`resource name` - `dataset name` - Data Catalogue

I've also updated one static title:

**Dataset search**
<del>Datasets</del>
Datasets - Data Catalogue

**Comment by joe-taylor** [comment]
For UAT, page title changes will be visible in the tab names.

**Comment by sheilamv** [comment]
STR:
1. From Dataset page, select **Metadata for Career Paths for Skilled Immigrants** dataset record (https://toyger.data.gov.bc.ca/dataset)
2. Validate that the url has changed to append the name of the dataset
Expected:  https://toyger.data.gov.bc.ca/dataset/metadata-for-career-paths-for-skilled-immigrants
Actual:  as expected

PASSED

**Comment by sheilamv** [comment]
Tested as explained by Joe and passed.

**Comment by sheilamv** [comment]
Tested in Beta - **PASSED**

![image](https://user-images.githubusercontent.com/65407822/134395738-a42dad19-f18e-41a7-b76d-fb6c893df72b.png)
