### ISSUE TITLE
Dataset View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#56]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- Should increase the distance (while maintaining the consistency with other views) between the left section and the right section so that they are visually more separated from each other.
- The position of the right section should be fixed instead of static.

### Left Section
- Remove the breadcrumb.
- The “{arrow-left} Back to Results (171)” link is missing, should be BC Sans - Regular - 16px - #1A5A96.
- “Dataset Details” should be BC Sans - Bold - 16px - #38598A, background color #1A5A96, height 40px, no shadow.
- Remove the extra space on the left of the content flow under “Dataset Details”.
- Dataset title is missing, should be be BC Sans - Bold - 23px - #494949.
- Field labels should be BC Sans - Bold - 16px - #494949.
- Help tooltip icons {help-circle-outline} are missing, #1A5A96.
- Field text should be BC Sans - Regular - 16px - #494949 or #1A5A96 as indicated.
- Revise copy and order of the fields to match what’s in the mockup, such as remove colons, etc.
- Horizontal line breaks should be 1px - Solid - #CCCCCC.

### Right Section
- “Resources” should be BC Sans - Bold - 16px - #38598A, background color #1A5A96, height 40px, no shadow.
- “test resource” should be “Test Resource”, BC Sans - Bold - 16px - #494949.
- “HTML” should be BC Sans - Bold - 16px - #494949.
- Reduce the distance between the ellipses icon and the right edge to be the same as what’s on the left.
- Remove the “Preview” option.
- “Download”, “View”, “Edit” options should be BC Sans - Regular - 16px - #1A5A96.
- “Delete” option should be BC Sans - Regular - 16px - #D8292F.
- Should allow clicking on the cards to have the same functionality as clicking on the “View” option.
- “Add New Resource” is missing.
- “{pencil-outline} Edit Dataset” should be BC Sans - Regular - 16px - #1A5A96.
- “{delete-outline} Delete Dataset” should be BC Sans - Regular - 16px - #D8292F.
- “PERMALINK” should be “{content-copy} Copy Permalink”, BC Sans - Regular - 16px - #1A5A96, no extra space on the left.
- “SHOW GROUPS” should be “{folder-table-outline} View the group(s) this dataset belongs to”, BC Sans - Regular - 16px - #1A5A96, no extra space on the left.

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Mockup with Guides
![image](https://user-images.githubusercontent.com/58751681/79617964-9aa68500-80bd-11ea-99c7-02c6663e70eb.png)

### Overall
- All fonts should be BC Sans, some texts on the page are still “Roboto”.
- The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
- Should increase the distance (while maintaining the consistency with other views) between the left section and the right section so that they are visually more separated from each other.
- Make the left and right sections scrollable separately from each other if achievable. The lower part of the right section is invisible due to the overflow.
- Remove the extra white gap under the Header.

### Left Section
- “{arrow-left} Back to Datasets list” should be “{arrow-left} Back to Results (171)”
- “Dataset Details” should be BC Sans - Bold - 16px, bar height 40px.
- Dataset title should be above the State field, BC Sans - Bold - 23px - #494949.
- Help tooltip icons {help-circle-outline} are missing, #1A5A96.
- Field text should be #494949 for regular texts or #1A5A96 for links.
- Please revise the copy and order of the fields to match what’s in the mockup.

### Right Section
- “Resources” should be BC Sans - Bold - 16px, bar height 40px.
- File format and size should be BC Sans - Regular - 16px - #494949.
- Clicking on the ellipsis icon should open the dropdown menu instead of jumping to the Resource View.
- “Download”, “View”, “Edit” options should be BC Sans - Regular - 16px - #1A5A96.
- “Delete” option should be BC Sans - Regular - 16px - #D8292F.
- “Add New Resource” isn’t functioning, should be BC Sans - Regular - 16px - #1A5A96.
- “{pencil-outline} Edit Dataset” is invisible, should be BC Sans - Regular - 16px - #1A5A96.
- “{delete-outline} Delete Dataset” is invisible, should be BC Sans - Regular - 16px - #D8292F.

**Comment by jachurchill** [comment]
Overall
* All fonts should be BC Sans, some texts on the page are still “Roboto”.
    * Done
* The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
    * Done
* Should increase the distance (while maintaining the consistency with other views) between the left section and the right section so that they are visually more separated from each other.
    * Done
* Make the left and right sections scrollable separately from each other if achievable. The lower part of the right section is invisible due to the overflow.
    * No longer fixed
* Remove the extra white gap under the Header.
    * Done

Left Section
* “{arrow-left} Back to Datasets list” should be “{arrow-left} Back to Results (171)”
    * Difficult to pull off
* “Dataset Details” should be BC Sans - Bold - 16px, bar height 40px.
    * Done
* Dataset title should be above the State field, BC Sans - Bold - 23px - #494949.
    * Done
* Help tooltip icons {help-circle-outline} are missing, #1A5A96.
    * They need text to be added by someone who knows what they should say
* Field text should be #494949 for regular texts or #1A5A96 for links.
    * Done
* Please revise the copy and order of the fields to match what’s in the mockup.
    * Not yet Done

Right Section
* “Resources” should be BC Sans - Bold - 16px, bar height 40px.
    * Done
* File format and size should be BC Sans - Regular - 16px - #494949.
    * Done
* Clicking on the ellipsis icon should open the dropdown menu instead of jumping to the Resource View.
    * Done
* “Download”, “View”, “Edit” options should be BC Sans - Regular - 16px - #1A5A96.
    * Done
* “Delete” option should be BC Sans - Regular - 16px - #D8292F.
    * Done
* “Add New Resource” isn’t functioning, should be BC Sans - Regular - 16px - #1A5A96.
    * Done
* “{pencil-outline} Edit Dataset” is invisible, should be BC Sans - Regular - 16px - #1A5A96.
    * Done
* “{delete-outline} Delete Dataset” is invisible, should be BC Sans - Regular - 16px - #D8292F.
    * Done

**Comment by SteveChapmanBCDX** [comment]
Ticket completed - closing.
