### ISSUE TITLE
Resource View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#57]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- Should increase the distance (while maintaining the consistency with other views) between the left section and the right section so that they are visually more separated from each other.
- The position of the right section should be fixed instead of static.

### Left Section
- “{arrow-left} BACK TO DATASET” should be “{arrow-left} Back to Dataset”, BC Sans - Regular - 16px - #1A5A96, and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View, remove containing rectangle.
- “Resource Details” should be BC Sans - Bold - 16px - #38598A, background color #1A5A96, height 40px, no shadow.
- Remove the extra space on the left of the content flow under “Resource Details”.
- Field labels should be BC Sans - Bold - 16px - #494949.
- Help tooltip icons {help-circle-outline} are missing, #1A5A96.
- Field text should be BC Sans - Regular - 16px - #494949.
- Revise copy and order of the fields to match what’s in the mockup, such as remove colons, etc.
- Horizontal line breaks should be 1px - Solid - #CCCCCC, and located as indicated.

### Right Section
- “Access” should be BC Sans - Bold - 16px - #38598A, background color #1A5A96, height 40px, no shadow.
- “DOWNLOAD” should be “{cloud-download-outline} Download”, BC Sans - Bold - 16px - #FFFFFF, background color #003366, border-radius 4px, height 50px, no shadow, same width as “Access”.
- “REQUEST ACCESS” should be “{folder-information-outline} Request Access”, BC Sans - Bold - 16px - #FFFFFF, background color #003366, border-radius 4px, height 50px, no shadow, same width as “Access”.
- “PREVIEW” should be “{fullscreen} Load Preview”, BC Sans - Bold - 16px - #003366, background color #FFFFFF, border 2px - solid - #003366, border-radius 4px, height 50px, no shadow, same width as “Access”.
- “Resources” should be “Other Resources”, BC Sans - Bold - 16px - #38598A, background color #1A5A96, height 40px, no shadow.
- Reduce the distance between the ellipses icon and the right edge to be the same as what’s on the left.
- Remove the “Preview” option.
- “Download”, “View”, “Edit” options should be BC Sans - Regular - 16px - #1A5A96.
- “Delete” option should be BC Sans - Regular - 16px - #D8292F.
- Should allow clicking on the cards to have the same functionality as clicking on the “View” option.
- “{pencil-outline} Edit Resource” should be BC Sans - Regular - 16px - #1A5A96.
- “{delete-outline} Delete Resource” should be BC Sans - Regular - 16px - #D8292F.
- “PERMALINK” should be “{content-copy} Copy Permalink”, BC Sans - Regular - 16px - #1A5A96, no extra space on the left, clicking on it should show a snack bar that states, “Copied to clipboard!” and disappears automatically in 2 seconds, same for the one on the Dataset View.

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Mockup with Guides
![image](https://user-images.githubusercontent.com/58751681/79618146-1e607180-80be-11ea-998e-d9b8f5d7de0c.png)


### Overall
- All fonts should be BC Sans, some texts on the page are still “Roboto”.
- The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
- Should increase the distance (while maintaining the consistency with other views) between the left section and the right section so that they are visually more separated from each other.
- Make the left and right sections scrollable separately from each other if achievable. The lower part of the right section is invisible due to the overflow.
- Remove the extra white gap under the Header.

### Left Section
- “{arrow-left} Back to Dataset” should be #1A5A96 for both icon and text.
- “Resource Details” should be BC Sans - Bold - 16px, bar height 40px.
- Help tooltip icons {help-circle-outline} are missing, #1A5A96.
- Field text should be #494949 for regular texts or #1A5A96 for links.
- Please revise the copy and order of the fields to match what’s in the mockup.
- Horizontal line breaks should be 1px - Solid - #CCCCCC, and located as indicated in the mockup.

### Right Section
- “Access” should be BC Sans - Bold - 16px, bar height 40px.
- “{cloud-download-outline} Download” should have the same width as “Access”.
- “{folder-information-outline} Request Access should have the same width as “Access”.
- “{fullscreen} Load Preview” should have the same width as “Access”.
- “Other Resources” should be BC Sans - Bold - 16px, bar height 40px.
- Clicking on the ellipsis icon should open the dropdown menu instead of reloading to the Resource View.
- “Download”, “View”, “Edit” options should be BC Sans - Regular - 16px - #1A5A96.
- “Delete” option should be BC Sans - Regular - 16px - #D8292F.
- “{pencil-outline} Edit Resource” is invisible due to overflow, should be BC Sans - Regular - 16px - #1A5A96.
- “{delete-outline} Delete Resource” is invisible due to overflow, should be BC Sans - Regular - 16px - #D8292F.
- “{content-copy} Copy Permalink” is invisible due to overflow, should be BC Sans - Regular - 16px - #1A5A96, no extra space on the left, clicking on it should show a snack bar that states, “Copied to clipboard!” and disappears automatically in 2 seconds, same for the one on the Dataset View.

**Comment by jachurchill** [comment]
Overall
* All fonts should be BC Sans, some texts on the page are still “Roboto”.
    * Done
* The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
    * Done
* Should increase the distance (while maintaining the consistency with other views) between the left section and the right section so that they are visually more separated from each other.
    * Done
* Make the left and right sections scrollable separately from each other if achievable. The lower part of the right section is invisible due to the overflow.
    * Not Done but position is no longer fixed
* Remove the extra white gap under the Header.
    * Done

Left Section
* “{arrow-left} Back to Dataset” should be #1A5A96 for both icon and text.
    * Done
* “Resource Details” should be BC Sans - Bold - 16px, bar height 40px.
    * Done
* Help tooltip icons {help-circle-outline} are missing, #1A5A96.
    * Done from code perspective, need to be added to schema when text is provided
* Field text should be #494949 for regular texts or #1A5A96 for links.
    * Done
* Please revise the copy and order of the fields to match what’s in the mockup.
    * TBD
* Horizontal line breaks should be 1px - Solid - #CCCCCC, and located as indicated in the mockup.
    * Done

Right Section
* “Access” should be BC Sans - Bold - 16px, bar height 40px.
    * Done
* “{cloud-download-outline} Download” should have the same width as “Access”.
    * Done
* “{folder-information-outline} Request Access should have the same width as “Access”.
    * Done
* “{fullscreen} Load Preview” should have the same width as “Access”.
    * Done
* “Other Resources” should be BC Sans - Bold - 16px, bar height 40px.
    * Done
* Clicking on the ellipsis icon should open the dropdown menu instead of reloading to the Resource View.
    * Done
* “Download”, “View”, “Edit” options should be BC Sans - Regular - 16px - #1A5A96.
    * Done
* “Delete” option should be BC Sans - Regular - 16px - #D8292F.
    * Done
* “{pencil-outline} Edit Resource” is invisible due to overflow, should be BC Sans - Regular - 16px - #1A5A96.
    * Done
* “{delete-outline} Delete Resource” is invisible due to overflow, should be BC Sans - Regular - 16px - #D8292F.
    * Done
* “{content-copy} Copy Permalink” is invisible due to overflow, should be BC Sans - Regular - 16px - #1A5A96, no extra space on the left, clicking on it should show a snack bar that states, “Copied to clipboard!” and disappears automatically in 2 seconds, same for the one on the Dataset View.
    * Done

**Comment by SteveChapmanBCDX** [comment]
View implemented - closing ticket.
