### ISSUE TITLE
Organizations View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#58]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- The left and right edges of the content flow should align with what’s in Header and Footer.
- Should increase the distance between the left section and the right section so that they are visually more separated from each other.
- The distance between Header and the content flow should be 50 pixels.
- The distance between the content flow and Footer should be 50 pixels.
- The position of the right section should be fixed instead of static.
- “Manage” and “Add Organization” in the “Organizations View Admin View - Desktop” are missing.

### Search Bar
- Background color should be #FFFFFF.
- Border should be 2px solid #003366.
- Border-radius should be 3px.
- The Search icon should be #CCCCCC.
- Box-shadow should be none.

### Organization Count
- Should be closer to the search bar like what’s on the Datasets View.

### Top-Tier Organizations
- Should be in alphabetical order.
- Text should be BC Sans - Bold - 16px.
- Background color should be #38598A.
- The Expand/Collapse icons should be on the left.

### Sub-Tier Organizations
- Should be in alphabetical order.
- Text should be BC Sans - Bold - 16px - #1A5A96.
- There should be space between the top-tier organization and its first sub-tier organization.

### Organizations Introduction Title
- The height should be the same as each organization title.
- Text should be BC Sans - Bold - 16px - #FFFFFF.
- Background color should be #38598A.
- Border-radius should be 0.

### Organizations Introduction Content
- Text should be BC Sans - Bold - 16px - #494949.
- The box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%).

**Comment by BrandonSharratt** [comment]
Overall
_Font should be BC Sans._
Fixed as part of 55

_Background color should be #F2F2F2._
Done

_The left and right edges of the content flow should align with what’s in Header and Footer._
Done

_Should increase the distance between the left section and the right section so that they are visually more separated from each other._
Done

_The distance between Header and the content flow should be 50 pixels.
The distance between the content flow and Footer should be 50 pixels._
Added my-4 for scaling reasons

_The position of the right section should be fixed instead of static._
Done

_“Manage” and “Add Organization” in the “Organizations View Admin View - Desktop” are missing._
They were added as part of adding the Organization view

**Comment by BrandonSharratt** [comment]
Search Bar
_Background color should be #FFFFFF.
Border should be 2px solid #003366.
Border-radius should be 3px.
The Search icon should be #CCCCCC.
Box-shadow should be none._
Copied from datasets page (#55)

**Comment by BrandonSharratt** [comment]
Organization Count
_Should be closer to the search bar like what’s on the Datasets View._
Not sure what you're looking for we don't have access to the dataset count. so the only thing missing from the mockups is the word found...added

**Comment by BrandonSharratt** [comment]
Top-Tier Organizations
_Should be in alphabetical order._

_Text should be BC Sans - Bold - 16px._
Done

_Background color should be #38598A._
Done

_The Expand/Collapse icons should be on the left._
Vuetify expansion panels do not support left icons

**Comment by BrandonSharratt** [comment]
Sub-Tier Organizations
_Should be in alphabetical order._
Done
_Text should be BC Sans - Bold - 16px - #1A5A96._
Done
_There should be space between the top-tier organization and its first sub-tier organization._
Done

**Comment by BrandonSharratt** [comment]
Organizations Introduction Content
_Text should be BC Sans - Bold - 16px - #494949._
Done

_The box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%)._
Done

**Comment by SteveChapmanBCDX** [comment]
Reassigning these to Nan/Yui for review.

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Overall
- The left and right edges of the content flow should VISUALLY (remove extra padding or margin?) align with what’s in Header and Footer.
![image](https://user-images.githubusercontent.com/58751681/78941815-3e17ea00-7a6d-11ea-9685-60e7ae75d7c2.png)
![image](https://user-images.githubusercontent.com/58751681/78941844-4cfe9c80-7a6d-11ea-9ec8-39b64449eddd.png)
![image](https://user-images.githubusercontent.com/58751681/78941862-57b93180-7a6d-11ea-98a1-c2668c7f5c61.png)
- Should increase the distance between the left section and the right section so that they are visually more separated from each other (while keeping the widths of both right and left sections the same as what’s in other views for consistency purpose).
- The position of the right section should be fixed instead of static (scrollable separately from the left section, currently it’s overflowing outside the viewport).

### “Organizations” Title
- Should be BC Sans - Bold - 23px - #1A5A96.

### Search Bar
- Please refer to the Datasets View (#55) for the change requests since this component is copied from there and should keep consistent with what’s there.
- “Search Organizations found” should be “Search for organization”, BC Sans - Regular - 16px - #494949.

### Organization Count
- “27 Organizations” should have the same style as the dataset count on the Datasets View (#55).

### Organization List
- Each organization should have it’s own bar, height 40 pixels, the hierarchy is addressed only by the color and width differences, please refer to the mockups.
- Remove the underline when clicked on.

### Top-Tier Organizations

### Sub-Tier Organizations
- Text should be BC Sans - Bold - 16px - #1A5A96.

### “Manage”
- The height should be 40 pixels (the same as each organization bar).
- Border-radius should be 0.
- Text should be vertically centered.

### “Add Organization”
- The height should be 50 pixels.
- Border-radius should be 0.
- Text should be BC Sans - Bold - 16px - #FFFFFF.

### Organizations Introduction Title
- The height should be 40 pixels (the same as each organization bar).
- Border-radius should be 0.
- Text should be vertically centered.

### Organizations Introduction Content
- Should be in it’s own card, please refer to the mockups.
- Text should be BC Sans - Regular - 16px - #494949.

**Comment by jachurchill** [comment]
Overall
* The left and right edges of the content flow should VISUALLY (remove extra padding or margin?) align with what’s in Header and Footer.
    * Done
* Should increase the distance between the left section and the right section so that they are visually more separated from each other (while keeping the widths of both right and left sections the same as what’s in other views for consistency purpose).
    * Done
* The position of the right section should be fixed instead of static (scrollable separately from the left section, currently it’s overflowing outside the viewport).
    * Done

“Organizations” Title
* Should be BC Sans - Bold - 23px - #1A5A96.
    * Done

Search Bar
* Please refer to the Datasets View (#55) for the change requests since this component is copied from there and should keep consistent with what’s there.
    * Done
* “Search Organizations found” should be “Search for organization”, BC Sans - Regular - 16px - #494949.
    * Done except font weight

Organization Count
* “27 Organizations” should have the same style as the dataset count on the Datasets View (#55).
    * Done 

Organization List
* Each organization should have it’s own bar, height 40 pixels, the hierarchy is addressed only by the color and width differences, please refer to the mockups.
    * Done
* Remove the underline when clicked on.
    * Done

Top-Tier Organizations
Sub-Tier Organizations
* Text should be BC Sans - Bold - 16px - #1A5A96.
    * Done

“Manage”
* The height should be 40 pixels (the same as each organization bar).
    * Done
* Border-radius should be 0.
    * Done
* Text should be vertically centered.
    * Done

“Add Organization”
* The height should be 50 pixels.
    * Done
* Border-radius should be 0.
    * Done
* Text should be BC Sans - Bold - 16px - #FFFFFF.
    * Done

Organizations Introduction Title
* The height should be 40 pixels (the same as each organization bar).
    * Done
* Border-radius should be 0.
    * Done
* Text should be vertically centered.
    * Done

Organizations Introduction Content
* Should be in it’s own card, please refer to the mockups.
    * Done
* Text should be BC Sans - Regular - 16px - #494949.
    * Done

**Comment by SteveChapmanBCDX** [comment]
View implemented - closing ticket.
