### ISSUE TITLE
Organization View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#59]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- The left and right edges of the content flow should align with what’s in Header and Footer.
- Should increase the distance between the left section and the right section so that they are visually more separated from each other (while maintaining the consistency with other views).
- The distance between Header and the content flow should be 50 pixels.
- The distance between the content flow and Footer should be 50 pixels.
- The position of the right section should be fixed instead of static.

### Dataset List, Pagination, Filters
- Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).

### Search Bar, Dataset Count
- Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).
- “Search Datasets in this organization” should be “Search for datasets in this organization”.

### Left Section
- “{arrow-left} Back to organization list” should be “{arrow-left} Back to Organizations List”, BC Sans - Regular - 16px - #1A5A96, and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View, remove containing rectangle.
- Breadcrumb should be BC Sans - Bold - 23px - #1A5A96 for links & #494949 for “/”.

### Right Section

- “Learn more about this organization” should be BC Sans - Regular - 16px - #1A5A96.
- “{content-copy} Copy Permalink” should be BC Sans - Regular - 16px - #1A5A96.
- Remove “{minus-circle-outline} Unfollow Organization”/“{plus-circle-outline} Follow Organization”.
- “{pencil-outline} Edit Organization” should be use the outline icon,  BC Sans - Bold - 16px - #1A5A96.
- “{delete-outline} Delete Organization” should be use the outline icon, BC Sans - Bold - 16px - #D8292F.

**Comment by BrandonSharratt** [comment]
Overall
_Font should be BC Sans._
Done as part of a different ticket

_Background color should be #F2F2F2._
Done

_The left and right edges of the content flow should align with what’s in Header and Footer._
Done

_Should increase the distance between the left section and the right section so that they are visually more separated from each other (while maintaining the consistency with other views)._
Done

_The distance between Header and the content flow should be 50 pixels._
The distance between the content flow and Footer should be 50 pixels._
Added my-4

_The position of the right section should be fixed instead of static._
As with Dataset page it doesn't work

**Comment by BrandonSharratt** [comment]
Dataset List, Pagination, Filters
_Keep consistent with what’s in the Datasets View (need to be refined based on review notes there)._

This uses the same components so all of that has been copied over

**Comment by BrandonSharratt** [comment]
Search Bar, Dataset Count
_Keep consistent with what’s in the Datasets View (need to be refined based on review notes there)._
This uses the same components and so has been copied over

_“Search Datasets in this organization” should be “Search for datasets in this organization”._
Done

**Comment by BrandonSharratt** [comment]
Left Section
_“{arrow-left} Back to organization list” should be “{arrow-left} Back to Organizations List”, BC Sans - Regular - 16px - #1A5A96, and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View, remove containing rectangle._
Done except not sure what the dataset view space is, and it doesn't have a containing rectangle?

Breadcrumb should be BC Sans - Bold - 23px - #1A5A96 for links & #494949 for “/”.
Done

**Comment by BrandonSharratt** [comment]
Right Section
_“Learn more about this organization” should be BC Sans - Regular - 16px - #1A5A96._
Done

_“{content-copy} Copy Permalink” should be BC Sans - Regular - 16px - #1A5A96._
Done

_Remove “{minus-circle-outline} Unfollow Organization”/“{plus-circle-outline} Follow Organization”._
Done

_“{pencil-outline} Edit Organization” should be use the outline icon, BC Sans - Bold - 16px - #1A5A96._
Done

_“{delete-outline} Delete Organization” should be use the outline icon, BC Sans - Bold - 16px - #D8292F._
Done

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Mockup with Guides
![image](https://user-images.githubusercontent.com/58751681/79508746-fd7d1b00-7fee-11ea-9c2e-a4a1ecbc32cf.png)

### Current State in Toyger
![image](https://user-images.githubusercontent.com/58751681/79508785-1259ae80-7fef-11ea-88e9-15b8d1e720ae.png)

### Overall

- The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
- The position of the right section should be fixed instead of static (scrollable separately from the left section when expanded if achievable). We want the user to have access to the filter wherever the user is vertically on the datasets list.

### Edit Mode
- Image URL field placeholder should be in regular font weight
- Image URL field label and the placeholder that becomes label (as per material design spec) is clashing, so can we make it so that the placeholder doesn’t turn into the label?

### Alignment
- Line up left edges of "← Back to ...", breadcrumbs, search bar, results count, and results with the left edge of the BC Mark (when it's updated with proper PNG).

### Dataset List, Pagination, Filters
- Keep consistent with what’s in the Datasets View (#55 need to be refined based on review notes there).

### Search Bar, Dataset Count
- Keep consistent with what’s in the Datasets View (#55 need to be refined based on review notes there).

### Left Section
- “{arrow-left} Back to Organization list” should be “{arrow-left} Back to Organizations List”, #1A5A96 (for both icon and text), and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View (please refer to the mockups if unsure).
- Breadcrumb should have #494949 for “/” and no underline for links.

### Right Section
- “Learn more about this organization” should be #1A5A96.
- “{content-copy} Copy Permalink” should be #1A5A96.
- “{pencil-outline} Edit Organization” should be #1A5A96.
- Add a little space between the icons and the button labels (Copy Permalink/Edit/Delete).

**Comment by jachurchill** [comment]
Overall
* The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
    * Done
* The position of the right section should be fixed instead of static (scrollable separately from the left section when expanded if achievable). We want the user to have access to the filter wherever the user is vertically on the datasets list.
    * Not static so that filters don’t go below window

Edit Mode
* Image URL field placeholder should be in regular font weight
    * Done
* Image URL field label and the placeholder that becomes label (as per material design spec) is clashing, so can we make it so that the placeholder doesn’t turn into the label?
    * Done

Alignment
* Line up left edges of "← Back to ...", breadcrumbs, search bar, results count, and results with the left edge of the BC Mark (when it's updated with proper PNG).
    * Done

Dataset List, Pagination, Filters
* Keep consistent with what’s in the Datasets View (#55 need to be refined based on review notes there).
    * Done

Search Bar, Dataset Count
* Keep consistent with what’s in the Datasets View (#55 need to be refined based on review notes there).
    * Done

Left Section
* “{arrow-left} Back to Organization list” should be “{arrow-left} Back to Organizations List”, #1A5A96 (for both icon and text), and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View (please refer to the mockups if unsure).
    * Done
* Breadcrumb should have #494949 for “/” and no underline for links.
    * Done

Right Section
* “Learn more about this organization” should be #1A5A96.
    * Done
* “{content-copy} Copy Permalink” should be #1A5A96.
    * Done
* “{pencil-outline} Edit Organization” should be #1A5A96.
    * Done
* Add a little space between the icons and the button labels (Copy Permalink/Edit/Delete).
    * Done

**Comment by SteveChapmanBCDX** [comment]
View implemented - closing ticket.
