### ISSUE TITLE
Test Skype for Business Workflow

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#73]

**Comment by yuisotozaki** [comment]
Skype for Business can be used to observe both the user's face and their actions on the screen.
We want to identify the step-by-step procedure so that we can reproduce it smoothly during test sessions.
The identified steps will be documented here: https://documize.pathfinder.gov.bc.ca/s/bkph5eb5fb79okvk8ffg/data-discovery-and-management/d/bp261mnf7ss5649lh7h0/bcdc-uiux-design-notes?currentPageId=bpj6j08kgd7clt4om2eg
